[package]
name = "rdma-core"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/linux-rdma/rdma-core/releases/download/v53.0/rdma-core-53.0.tar.gz"
sha512 = "c0e6fc79247f3a22f58e4fde03eba54502ec9503dbd5e36b9094ce9cd26e324692c58ba6b737ae8dec84459392dd1f87d4969df418a1631238f5739b81c0f91f"

[build-dependencies]
glibc = { path = "../glibc" }
libnl = { path = "../libnl" }
